FROM php:8.2-fpm as php-8

# Set working directory
WORKDIR /var/www

# Add docker php ext repo
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Install php extensions
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions mbstring pdo_mysql zip exif pcntl gd memcached

# Install dependencies
RUN apt-get update 
# && apt-get install -y \
#     build-essential \
#     libpng-dev \
#     libjpeg62-turbo-dev \
#     libfreetype6-dev \
#     locales \
#     zip \
#     jpegoptim optipng pngquant gifsicle \
#     unzip \
#     git \
#     curl \
#     lua-zlib-dev \
#     libmemcached-dev \
#     php8.2-imagick

RUN apt-get install -y build-essential
RUN apt-get install -y libpng-dev libjpeg62-turbo-dev libfreetype6-dev
RUN apt-get install -y locales zip jpegoptim optipng pngquant gifsicle
RUN apt-get install -y unzip git curl lua-zlib-dev libmemcached-dev
RUN apt-get install -y libmagickwand-dev
RUN apt-get install -y libgd-dev
# Install Imagick extension using pecl
RUN pecl install imagick \
    && docker-php-ext-enable imagick

RUN docker-php-ext-install mysqli pdo pdo_mysql



# Install supervisor
RUN apt-get install -y supervisor

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*


# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy code to /var/www
COPY --chown=www:www-data . /var/www

# add root to www group
# RUN chmod -R ug+w /var/www/storage


# Copy php/supervisor configs
# RUN cp docker/supervisor.conf /etc/supervisord.conf
# RUN cp docker/php.ini /usr/local/etc/php/conf.d/app.ini

# PHP Error Log Files
RUN mkdir /var/log/php
RUN touch /var/log/php/errors.log && chmod 777 /var/log/php/errors.log

# Deployment steps
# RUN composer install --optimize-autoloader --no-dev
# RUN touch ~/.bashrc && chmod +x ~/.bashrc
# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
# RUN . ~/.nvm/nvm.sh && /bin/bash -c "source ~/.bashrc" 
# RUN nvm install node


# EXPOSE 9000
