version: '3.9'

services:
  web:
    image: nginx:latest
    container_name: nginx_container1
    ports: 
      - '80:80'
    volumes:
    #D:\repository\docker\nginx_php_python_node\Dockerfile\docker-compose.yml
      - /home/sujig20/code/:/var/www/
      # - /d/projects/code/work/php/:/var/www/
     # - /d/projects/code/php/conffiles/dms_scm_config.php:/var/www/dms.mi.com/config/scm_config.php
      - /home/sujig20/nginx_php_python_node_gcp-/Dockerfile/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/sujig20/nginx_php_python_node_gcp-/Dockerfile/conf/nginx/sites-available/:/etc/nginx/conf.d/vhosts/sites-enabled/
      - /home/sujig20/nginx_php_python_node_gcp-/Dockerfile/conf/nginx/sites-available/:/etc/nginx/conf.d/vhosts/sites-available/
    links:
      - php
    # network_mode: "host"
    networks:
      - mynetwork

  php:
    image: kumargowtham/nginx_php_python_node:v6
    container_name: php_container1
    volumes:
      - /home/sujig20/code/:/var/www/
      # - /d/projects/code/work/php/:/var/www/
      # - /d/projects/code/php/conffiles/dms_scm_config.php:/var/www/dms.mi.com/config/scm_config.php
      # - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./conf/nginx/sites-enabled/:/etc/nginx/conf.d/vhosts/sites-enabled/
    networks:
      - mynetwork
  # react:
  #   image: react
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - /d/projects/study/react/ecom3-ui:/app
  db:
    image: mysql:8.0
    container_name: db_container1
    restart: always
    environment: 
      MYSQL_DATABASE: 'db'
      #So you dont have to use root. you can use if you like to use
      MYSQL_USER: 'user'
      #you can use whatever password you like
      MYSQL_PASSWORD: 'pwd'
      #password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      #ports exposed
      - '3306:3306'
    expose:
      #ports open 3306 on the container
      - '3306'
      #where our data will be persisted                                                                                
    volumes:
      - my-db:/home/sujig20/db
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 80:80

  # mongo:

  # redis:
#Names our volumes
volumes:
  my-db:

networks:
  mynetwork:
    driver: bridge