services:
  web:
    image: nginx:latest
    container_name: nginx_container1
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ${FOLDER_PATH}/Dockerfile/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${FOLDER_PATH}/Dockerfile/conf/nginx/sites-available:/etc/nginx/conf.d/vhosts/sites-enabled/
      - ${FOLDER_PATH}/Dockerfile/conf/nginx/sites-available:/etc/nginx/conf.d/vhosts/sites-available/
      - ${PHP_CODE_PATH}/:/var/www/
      # - /etc/letsencrypt:/etc/letsencrypt/
    links:
      - php
    networks:
      - mynetwork

  php:
    image: kumargowtham/nginx_php_python_node:v6
    container_name: php_container1
    volumes:
      - ${PHP_CODE_PATH}/:/var/www/
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: db_container1
    restart: always
    environment: 
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pwd'
      MYSQL_ROOT_PASSWORD: 'root'
    command: --bind-address='0.0.0.0'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./conf/pma/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - mynetwork

volumes:
  my-db:

networks:
  mynetwork:
    driver: bridge